### ISSUE TITLE
Completion of the API

### ISSUE THREAD

**Issue by mmstick** [cholcombe973/blkid#4]
I have use for this in several projects at System76, so I am going to work on completing this, in addition to cleaning up what's already been written to make it more idiomatic to Rust API guidelines. I'll be working on this in my spare time, as it's not an immediate priority, though.

**Comment by cholcombe973** [comment]
Awesome!  Happy to have the contributions.  I look forward to seeing what you do.

**Comment by mmstick** [comment]
Current progress can be tracked [here](https://github.com/pop-os/blkid)

**Comment by cholcombe973** [comment]
Excellent!  I like how it's coming out.

**Comment by cholcombe973** [comment]
@mmstick did you want to PR your work back?  It looks more or less finished.

**Comment by mmstick** [comment]
Sure, I can do that

**Comment by Silverhorn27** [comment]
@cholcombe973 I think you can close this issue according to https://github.com/cholcombe973/blkid/pull/7.
