### ISSUE TITLE
Make crate more flexible to different versions of the library

### ISSUE THREAD

**Issue by Silverhorn27** [cholcombe973/blkid#8]
Unfortunately, when I started implement wrappers I used the latest version of library, but when I tried to compile crate on Debian 9 I figured out that's impossible, because this system doesn't have the latest version of `blkid` in repositories. That's kinda of annoying. To resolve this issue we need to use precompile conditions, in Rust I think it's a features compile conditions. A lot of people use `pkg-config` to find out version of library in system. Rust world has already a wrapper around this utility (follow to the link: https://docs.rs/pkg-config/latest/pkg_config/).
So, the idea is using `pkg-config` crate and setup compiling library code according to the versions of `blkid`.

**Comment by cholcombe973** [comment]
Yeah i think `pkg_config` looks like a reasonable way to handle that situation.
